### ISSUE TITLE
Verifying Argon2 Hash?

### ISSUE THREAD

**Issue by Nantris** [urbit/argon2-wasm#6]
@Fang- thanks again for your help with this library! Is there any way to verify an Argon2 hash as it stands now?

**Comment by Fang-** [comment]
Depends on what you mean by "verifying a hash". To test this for correct output, you can compare it against known answers and/or other implementations. Is that what you're looking to do?

**Comment by Nantris** [comment]
I wrote out all the below, though it looks like @antelle has already implemented it in the time it took me to clarify my thoughts: https://github.com/antelle/argon2-browser/issues/7#issuecomment-443872030

-----

Thanks for your reply @Fang- I guess a better way to state what I'm looking for would be: a feature to extract the parameters from the encoded hash and handle verifying that an entered password matches the one that originally produced the encoded hash.

Other Argon2 implementations I've used generate a salt internally and later extract the salt from the encoded hash. It's just a nice convenience to avoid storing all the parameters as separate entities. Most parameters are easy to pull from the encoded hash, but I'm not sure how to pull the salt from the encoded hash.

**Comment by Fang-** [comment]
Pretty sure one of the outputs of Argon2 is a string that includes all the parameters, along with the result? But I might be wrong, maybe we ended up wrapping around that here.

In any case, Argon2 for our (current) use case is one-way and we don't ever need to verify against the result. I wouldn't be opposed to adding the kind of functionality you describe, but the time:return ratio here is infinite for us, so we won't get to it anytime soon.

It also seems like @antelle's version's got you covered now, so pick up their version instead of ours. (:
